import { getProviderToken } from '../stores/main'

const changePlaylistDetails = async (
    playlistId: string,
    signal?: AbortSignal
) => {
    const providerToken = getProviderToken()
    try {
        await fetch(`https://api.spotify.com/v1/playlists/${playlistId}`, {
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json',
                Authorization: `Bearer ${providerToken}`,
            },
            body: JSON.stringify({
                description: `A playlist generated by the Shuffle Party app. Last modified ${new Date().toLocaleString('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false })} on ${new Date().toDateString().split(' ').slice(1).join(' ')}`,
            }),
            signal: signal,
        })
    } catch (error) {
        if ((error as Error).name === 'AbortError') {
            console.log('Fetch aborted')
        } else {
            throw new Error('Error changing playlist details: ' + error)
        }
    }
}

export default changePlaylistDetails
