import { getProviderToken } from '../stores/main'

const createPlaylist = async (signal?: AbortSignal) => {
    const providerToken = getProviderToken()
    try {
        const playlist = await fetch(
            `https://api.spotify.com/v1/me/playlists`,
            {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${providerToken}`,
                },
                body: JSON.stringify({
                    name: 'Shuffle Party',
                    public: true,
                    description: `A playlist generated by the Shuffle Party app. Last modified ${new Date().toDateString().split(' ').slice(1).join(' ')}`,
                }),
                signal: signal,
            }
        )
        return playlist.json()
    } catch (error) {
        if ((error as Error).name === 'AbortError') {
            console.log('Fetch aborted')
        } else {
            throw new Error('Error fetching tracks: ' + error)
        }
        return []
    }
}

export default createPlaylist
